/**
 * npm run cards:report — per-card completion status (blueprint CARD_IMPLEMENTATION_TRACKER):
 * writes data/cards/status.json and docs/CARD_STATUS_REPORT.md.
 *
 * A card is complete when: data officially verified (both official sites, stats agree) +
 * effect implemented (or the card has no abilities) + a card test names it (when it has
 * abilities) + art present. `npm test` must also pass (checked by CI / npm run check, not here).
 * Art lives in git-ignored assets/ (D-018), so art status reflects this machine.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { SETS } from '../../src/cards';
import { isSameAs, effectStatus } from '../../src/cards/load';

interface Status {
  data: 'officially_verified' | 'needs_review';
  effect: ReturnType<typeof effectStatus>;
  tests: 'covered' | 'none' | 'not_needed';
  art: 'present' | 'missing';
  complete: boolean;
  note?: string;
}

const status: Record<string, Status> = {};
const lines: string[] = ['# Card Status Report', '', `Generated by \`npm run cards:report\`.`, ''];

for (const { file, abilities } of SETS) {
  const testFile = `tests/cards/${file.set}.test.ts`;
  const tests = existsSync(testFile) ? readFileSync(testFile, 'utf8') : '';
  const artDir = `assets/cards/${file.set}`;
  const art = existsSync(artDir)
    ? new Set(readdirSync(artDir).map((f) => f.replace(/\.\w+$/, '')))
    : new Set<string>();
  const rows: string[] = [];
  for (const r of file.cards) {
    const effect = effectStatus(r, abilities);
    const entry = abilities[r.id];
    const hasAbilities = Array.isArray(entry) && entry.length > 0;
    const reprint = isSameAs(entry); // tested through the original card
    const s: Status = {
      data:
        r.sources.jp && r.sources.en && (r.checks.jpEnStatsMatch || r.checks.reviewed)
          ? 'officially_verified'
          : 'needs_review',
      effect,
      tests:
        !hasAbilities || reprint ? 'not_needed' : tests.includes(`'${r.id}'`) ? 'covered' : 'none',
      art: art.has(r.id) ? 'present' : 'missing',
      complete: false,
      ...(entry && !Array.isArray(entry) && !reprint
        ? { note: (entry as { needsReview: string }).needsReview }
        : {}),
    };
    s.complete =
      s.data === 'officially_verified' &&
      (effect === 'implemented' || effect === 'none') &&
      s.tests !== 'none' &&
      s.art === 'present';
    status[r.id] = s;
    if (!s.complete) {
      const why = [
        s.data !== 'officially_verified' && 'data',
        effect === 'missing' && 'effect missing',
        effect === 'needs_review' && `needs review: ${s.note}`,
        s.tests === 'none' && 'no test',
        s.art === 'missing' && 'no art',
      ].filter(Boolean);
      rows.push(`- ${r.id} ${r.en?.name ?? r.jp?.name} — ${why.join(', ')}`);
    }
  }
  const cards = file.cards.map((r) => status[r.id]!);
  const count = (f: (s: Status) => boolean) => cards.filter(f).length;
  lines.push(
    `## ${file.set}`,
    '',
    '| Total | Officially verified | Effects implemented | Effects missing | Needs review | Tests covered | Art | Complete |',
    '|---|---|---|---|---|---|---|---|',
    `| ${cards.length} | ${count((s) => s.data === 'officially_verified')} | ${count((s) => s.effect === 'implemented' || s.effect === 'none')} | ${count((s) => s.effect === 'missing')} | ${count((s) => s.effect === 'needs_review')} | ${count((s) => s.tests !== 'none')} | ${count((s) => s.art === 'present')} | ${count((s) => s.complete)} |`,
    '',
    rows.length ? '### Incomplete' : 'All cards complete.',
    '',
    ...rows,
    '',
  );
}

writeFileSync('data/cards/status.json', JSON.stringify(status, null, 2) + '\n');
writeFileSync('docs/CARD_STATUS_REPORT.md', lines.join('\n'));
console.log(lines.slice(4, 9).join('\n'));
