/**
 * Card data as stored in data/cards/<SET>.json (DECISIONS D-017). Generated by the importer from
 * the official Bushiroad databases; never edited by hand (corrections go in the importer's
 * override list with a reason, so they stay auditable).
 */
import type { SkillIcon, TriggerType } from '../engine/cards/types';

export interface SourceRef {
  readonly url: string;
  /** ISO date-time the page was fetched. */
  readonly fetchedAt: string;
  /** Regulation label the site shows (e.g. "G-Regulation"); empty if none. */
  readonly regulation: string;
}

export interface Localized {
  readonly number: string;
  readonly name: string;
  /** Printed ability text, one line per ability; empty for vanilla cards. */
  readonly text: string;
  readonly clan: string;
  readonly race: string;
  readonly image: string | null;
}

export interface CardRecord {
  /** Canonical ID, e.g. "BT01-002" (Japanese-original numbering, CARD_DATA policy §1). */
  readonly id: string;
  readonly set: string;
  readonly jp: Localized | null;
  readonly en: Localized | null;
  readonly cardType: 'normal_unit' | 'trigger_unit';
  readonly grade: number;
  readonly power: number;
  readonly shield: number;
  readonly critical: number;
  readonly skillIcon: SkillIcon | null;
  readonly trigger: TriggerType | null;
  readonly sentinel: boolean;
  readonly rarity: string;
  /** Every printing of this card in the set (base number first, then e.g. S/SP printings). */
  readonly printings: readonly string[];
  readonly sources: { readonly jp?: SourceRef; readonly en?: SourceRef };
  /** Automated cross-checks between the two official sources. */
  readonly checks: {
    readonly jpEnStatsMatch: boolean;
    readonly mismatches: readonly string[];
    /** Why a JP/EN difference is expected (a real regional printing difference, reviewed). */
    readonly reviewed?: string;
    /** Which printing's stats the game uses for a reviewed difference (default Japanese). */
    readonly statsFrom?: 'jp' | 'en';
  };
}

export interface SetFile {
  readonly set: string;
  readonly importedAt: string;
  readonly importerVersion: number;
  readonly cards: readonly CardRecord[];
  /**
   * Cards in the English product of this set that are not in the Japanese set (CARD_DATA policy
   * §8: regional product differences are recorded, never merged into the canonical set).
   */
  /**
   * A Trial Deck's fixed contents (card ID and copies), from the official English product page
   * (DECISIONS D-023).
   */
  readonly product?: {
    readonly name: string;
    readonly cards: readonly { readonly id: string; readonly count: number }[];
    readonly source: SourceRef;
  };
  readonly enOnly?: readonly {
    readonly number: string;
    readonly name: string;
    readonly printings: readonly string[];
  }[];
}
